version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/Stockholm
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: FakeItEasy
    versions:
    - 7.0.0
  - dependency-name: MSTest.TestFramework
    versions:
    - 2.2.1
    - 2.2.2
  - dependency-name: MSTest.TestAdapter
    versions:
    - 2.2.1
    - 2.2.2
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.2
    - 3.0.3
  - dependency-name: Microsoft.CodeAnalysis.CSharp.Workspaces
    versions:
    - 3.8.0
